# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/infinix/Infinix-X6816D/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/infinix/Infinix-X6816D

PRODUCT_COPY_FILES += \
    vendor/infinix/Infinix-X6816D/proprietary/etc/permissions/com.nxp.nfc.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.nxp.nfc.xml \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib/android.hardware.radio@1.5.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/android.hardware.radio@1.5.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib/vendor.sprd.hardware.radio.ims@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.sprd.hardware.radio.ims@1.0.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib/vendor.sprd.hardware.radio.ims@1.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.sprd.hardware.radio.ims@1.1.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib/vendor.sprd.hardware.radio.lite@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.sprd.hardware.radio.lite@1.0.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib/vendor.sprd.hardware.radio@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.sprd.hardware.radio@1.0.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib/vendor.sprd.hardware.radio@1.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.sprd.hardware.radio@1.1.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib/vendor.unisoc.hardware.power-V1-ndk_platform.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.unisoc.hardware.power-V1-ndk_platform.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib64/android.hardware.radio@1.5.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/android.hardware.radio@1.5.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib64/vendor.sprd.hardware.radio.ims@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.sprd.hardware.radio.ims@1.0.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib64/vendor.sprd.hardware.radio.ims@1.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.sprd.hardware.radio.ims@1.1.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib64/vendor.sprd.hardware.radio.lite@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.sprd.hardware.radio.lite@1.0.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib64/vendor.sprd.hardware.radio@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.sprd.hardware.radio@1.0.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib64/vendor.sprd.hardware.radio@1.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.sprd.hardware.radio@1.1.so \
    vendor/infinix/Infinix-X6816D/proprietary/system_ext/lib64/vendor.unisoc.hardware.power-V1-ndk_platform.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.unisoc.hardware.power-V1-ndk_platform.so

PRODUCT_PACKAGES += \
    ims \
    boot-unisoc-framework \
    boot-unisoc-framework \
    boot-unisoc-framework \
    boot-unisoc_ims_common \
    boot-unisoc_ims_common \
    boot-unisoc_ims_common \
    boot-unisoc-framework \
    boot-unisoc-framework \
    boot-unisoc-framework \
    boot-unisoc_ims_common \
    boot-unisoc_ims_common \
    boot-unisoc_ims_common \
    boot-unisoc-framework \
    boot-unisoc_ims_common \
    com.unisoc.sdk.common \
    unisoc-framework \
    unisoc-services \
    unisoc_ims_common \
    com.nxp.nfc
